<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Nop Commerce Project</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-24T14:20:48</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>38619d15-a714-42db-ba88-ab0bbbcdc0e3</testSuiteGuid>
   <testCaseLink>
      <guid>7caf3575-ebf0-4a55-bb71-2ec61dedcc48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/verify_User Registration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9743a817-33da-4429-95c1-0516bd1edaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>192432ef-13ad-4b9b-9ab1-ba70e09722d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d2dc27b-9be0-4b73-96da-59466b46e757</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5589efe5-c67e-4a42-a31a-9011b4be0eca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d76c6528-82d2-43ac-8c4e-4c156911f7c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc0cfa1a-21e5-4976-a5e3-251bd844db03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>516c2bf1-d233-4aa5-9b1b-8c7ef7210e1a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65f6aa47-cf6c-4fe3-81b9-b818918ba9b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify_Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f820c86-93bc-411a-bbb2-055ec6a6f367</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>902a1580-a1ac-434a-b5bc-d17916989414</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>861857da-46f8-49a8-ba7d-fc6b176e195c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2951c68d-9ba9-43f8-8342-427e2d8cb89f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44829d9d-74df-43f3-a4f5-6f395c752a6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Adding Nokia Lomia To Cart/verify add Nokia Lumia To Cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d50ff443-44ea-4fe6-9723-d3a91252d6e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b410c7c7-dd9f-4d2a-b2fd-ff56a60fd491</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify Add Flower Girl Bracelet To Cart/verify Add Flower Bracelet To cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ba0aba6-a18f-4b9b-8686-11ae4e288d98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9cb3050-1eef-402b-8a82-c84e5f79d409</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify Remove Nokia Lumia From Cart/Verify Remove Nokia Lumia From Cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8524f8a0-fe4c-4845-9bc2-ad17cb542b01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Scenarios On The Site/validate_Wrong Email Correct Password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51b41da5-f350-4c18-9e8b-caab9b91f1cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b28b629-5698-4807-b09a-0b0f2d90baf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31e70d85-7823-48af-ba81-920a9f6cf9e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8096bed-79a4-417d-8c99-47179c7842fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check Out/verify_Checkout</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b0a869-a60d-49bc-833e-f7165309557d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e09523f6-00b6-4a2e-a03a-ef31bed2b2ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>457353b1-fdc5-46b1-bf3e-747e0b60a609</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afcf675a-6290-4ac5-8727-23047c6d9f42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ab8a46b-5ece-40e9-bc7c-e30c1db37612</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07ab818b-42f0-414e-8772-00e57a4b5a95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c0a91ea-1420-43b6-a824-445a8706e003</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25f57eb6-9a1c-4118-9865-60e6b21d22d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac58e0e0-1836-4233-afce-26a4d4174a88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b0f5986-ba50-452c-b289-f3ba6a39cefe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7138c43-2910-4424-918d-560d6fb5524a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify Logout/Verify-Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
